In [ ]:
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr1=np.zeros((2,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.arange(2,20,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
arr2=np.arange(1,10)
print(np.shape(arr2))
print(np.ndim(arr3))
print(arr2.dtype)
print(len(arr2))
a=arr2
print(a*2)

(9,)
1
int64
9
[ 2  4  6  8 10 12 14 16 18]


In [ ]:
arr3=np.arange(1,10)
print(np.sum(arr3))
print(np.mean(arr3))
print(np.max(arr3))
print(np.min(arr3))
print(np.std(arr3))



45
5.0
9
1
2.581988897471611
